# https://taskfile.dev

version: "3"

vars:
  COMPOSE_FILE: docker/docker-compose.yml

tasks:
  default:
    cmd: task -a

  stack:build:
    cmd: docker compose -f {{.COMPOSE_FILE}} build

  stack:up:
    cmd: docker compose -f {{.COMPOSE_FILE}} up -d

  stack:down:
    cmd: docker compose -f {{.COMPOSE_FILE}} down

  stack:clean:
    cmd: docker compose -f {{.COMPOSE_FILE}} down -v

  stack:load-data:
    cmds:
      - kurra fuseki upload background-resources/ http://localhost:3030/ds
      - kurra fuseki upload vocabularies/ http://localhost:3030/ds
      - kurra fuseki upload prez/ http://localhost:3030/ds
      - rupdate --service http://localhost:3030/ds --update docker/namespaces.rq

  stack:up:init:
    cmds:
      - task: stack:up
      - task: stack:load-data
