# https://taskfile.dev

version: "3"

vars:
  COMPOSE_FILE: docker/docker-compose.yml
  FUSEKI_DATASET: gssa
  VOCPUB_VERSION: "4.10"

tasks:
  default:
    cmd: task -a

  stack:build:
    cmd: docker compose -f {{.COMPOSE_FILE}} build

  stack:up:
    cmd: FUSEKI_DATASET={{.FUSEKI_DATASET}} docker compose -f {{.COMPOSE_FILE}} up -d

  stack:down:
    cmd: docker compose -f {{.COMPOSE_FILE}} down

  stack:clean:
    cmd: docker compose -f {{.COMPOSE_FILE}} down -v

  stack:create-ds:
    desc: Create the gssa dataset
    cmd: kurra db create http://localhost:3030 {{.FUSEKI_DATASET}}

  stack:load-data:
    cmds:
      - kurra file upload background-resources/ http://localhost:3030/{{.FUSEKI_DATASET}}
      - kurra file upload vocabularies/ http://localhost:3030/{{.FUSEKI_DATASET}}
      - kurra file upload prez/ http://localhost:3030/{{.FUSEKI_DATASET}}
      - |
        curl -X POST http://localhost:3030/{{.FUSEKI_DATASET}}/update \
          -H "Content-Type: application/sparql-update" \
          --data-binary "$(cat prez-queries/namespaces.rq)"

  stack:up:init:
    cmds:
      - task: stack:up
      - task: stack:create-ds
      - task: stack:load-data

  validate:
    cmd: |
      for file in vocabularies/*.ttl; do
        echo "Validating $file..."
        pyshacl --allow-warnings --shapes vocpub.ttl "$file"
        if [ $? -ne 0 ]; then
          echo "Validation failed for $file"
          exit 1
        fi
      done
