services:
  fuseki:
    image: ghcr.io/kurrawong/fuseki-geosparql:git-main-e642d849
    ports:
      - 3030:3030
    volumes:
      - fuseki_data:/fuseki
      - ./shiro.ini:/fuseki/shiro.ini
      - ./config.ttl:/fuseki/config.ttl

    healthcheck:
      test: ["CMD","curl", "-f", "http://localhost:3030/$/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  prez:
    image: ghcr.io/rdflib/prez:4.1.3-dev.43.d5f5a2a
    ports:
      - 8000:8000
    environment:
      - SPARQL_ENDPOINT=http://fuseki:3030/ds
    depends_on:
      fuseki:
        condition: service_healthy

volumes:
  fuseki_data: