services:
  fuseki:
    build:
      context: .
      dockerfile: Dockerfile.fuseki
    ports:
      - 3030:3030
    volumes:
      - fuseki_data:/fuseki

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/$/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  prez:
    image: ghcr.io/rdflib/prez:4.1.3-dev.43.d5f5a2a
    ports:
      - 8000:8000
    environment:
      - SPARQL_ENDPOINT=http://fuseki:3030/${FUSEKI_DATASET}
      - SEARCH_METHOD=fts_fuseki
    depends_on:
      fuseki:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  prez-ui:
    build:
      context: .
      dockerfile: Dockerfile.prez-ui
      args:
        - NUXT_PUBLIC_PREZ_API_ENDPOINT=http://localhost:8000
    ports:
      - 3000:3000

volumes:
  fuseki_data:
