# sparql --data work-status.ttl --query ../scripts/make-labels-for-vocab.sparql --results nt
# sparql --query ../scripts/make-labels-for-vocab.sparql --results nt --data commodity-codes.sa.ttl >> ../background-resources/voc-labels.nt

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
    ?c rdfs:label ?nolang
}
WHERE {
    ?c skos:prefLabel ?pl .
    BIND (STR(?pl) AS ?nolang)
}
