trigger:
  branches:
    include:
      - main

jobs:
  - deployment: vocabs_dev_deployment
    environment: vocabs-dev
    pool:
      vmImage: "ubuntu-latest"
    variables:
      - group: vocabs-dev
    strategy:
      runOnce:
        deploy:
          steps:
            - template: ../templates/deploy.yml
              parameters:
                python_version: $(PYTHON_VERSION)
                bastion_file_name: "bastion_dev_id_rsa"
                bastion_host: $(BASTION_HOST)
                bastion_user: $(BASTION_USER)
                fuseki_domain_name: $(FUSEKI_DOMAIN_NAME)
                fuseki_username: $(FUSEKI_USERNAME)
                fuseki_password: $(FUSEKI_PASSWORD)
                fuseki_dataset: $(FUSEKI_DATASET)
