trigger:
  branches:
    include:
      - main

jobs:
  - deployment: vocabs_dev_deployment
    environment: vocabs-dev
    timeoutInMinutes: 10
    pool:
      vmImage: "ubuntu-latest"
    variables:
      - group: vocabs-dev
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadSecureFile@1
              name: sshKey
              displayName: "Download SSH Key"
              inputs:
                secureFile: bastion_dev_id_rsa

            - template: ../templates/deploy.yml
              parameters:
                python_version: $(PYTHON_VERSION)
                bastion_file_path: $(sshKey.secureFilePath)
                bastion_host: $(BASTION_HOST)
                bastion_user: $(BASTION_USER)
                fuseki_domain_name: $(FUSEKI_DOMAIN_NAME)
                fuseki_username: $(FUSEKI_USERNAME)
                fuseki_password: $(FUSEKI_PASSWORD)
                fuseki_dataset: $(FUSEKI_DATASET)
