trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: vocabs-dev

steps:
  - task: CmdLine@2
    displayName: "Install Taskfile"
    inputs:
      script: |
        sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
        echo '##vso[task.prependpath]~/.local/bin'
        task --version

  - task: CmdLine@2
    displayName: "Install uv"
    inputs:
      script: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo '##vso[task.prependpath]~/.local/bin'
        uv --version

  - task: CmdLine@2
    displayName: "Install python"
    inputs:
      script: |
        uv install python@$(PYTHON_VERSION)
        python --version

  - task: CmdLine@2
    displayName: "Install kurra"
    inputs:
      script: |
        uv tool install kurra
        kurra --version

  - task: CmdLine@2
    displayName: "Upload vocabularies"
    inputs:
      script: |
        kurra file upload vocabularies/ $(FUSEKI_URL)/$(FUSEKI_DATASET) --username $(FUSEKI_USERNAME) --password $(FUSEKI_PASSWORD)
