trigger:
  branches:
    exclude:
      - main

pool:
  vmImage: "ubuntu-latest"

variables:
  pythonVersion: "3.13"

steps:
  - displayName: "Install Taskfile"
    bash: |
      sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
      echo '##vso[task.prependpath]~/.local/bin'
      task --version

  - displayName: "Install uv"
    bash: |
      curl -LsSf https://astral.sh/uv/install.sh | sh
      echo '##vso[task.prependpath]~/.local/bin'
      uv --version

  - displayName: "Install python"
    bash: |
      uv install python@${{ variables.pythonVersion }}
      python --version

  - displayName: "Install pyshacl"
    bash: |
      uv tool install pyshacl
      pyshacl --version

  - displayName: "Validate vocabularies"
    bash: |
      task validate
